version: "3.8"

x-config-server: &spring-config
  environment:
    - SPRING_CLOUD_CONFIG_URI=http://demo1-config:8011

services:
  demo1-config:
    build:
      context: ./config
      dockerfile: ./Dockerfile
    image: demo1-config
    ports:
      - 8011:8011
    container_name: demo1-config
    # command: bash -c "jar -xf config.jar && java -cp BOOT-INF/classes:BOOT-INF/lib/* com.example.MyApplication"

  demo1-postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: user
      POSTGRES_DB: demo1
    container_name: demo1-postgres

  demo1-user:
    build:
      context: ./user
      dockerfile: ./Dockerfile
    image: demo1-user
    ports:
      - 8010:8010
    depends_on:
      - demo1-config
      - demo1-postgres
    <<: *spring-config
    command: bash -c "./wait-for-it.sh demo1-config:8011 && ./wait-for-it.sh demo2-postgres:5432 -- java -jar user.jar"
    # container_name: demo1-user
